version: "3"
services:
  web:
    container_name: web
    restart: always
    build: ./packages/web
    command: ["npm", "run", "dev"]
    volumes:
      - ./packages/web:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - GRAPHQL_URL_SERVER=http://api:8080/graphql
      - GRAPHQL_URL_CLIENT=http://localhost:3001/graphql
    depends_on:
      - api
  api:
    container_name: api
    restart: always
    build: ./packages/api
    command: ["npm", "run", "dev"]
    volumes:
      - ./packages/api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/development
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
